version: '3.8'

services:
  spring-docker:
    build: 
      dockerfile: Dockerfile
    container_name: spring-docker
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - workspace

networks:
  workspace:
    driver: bridge