version: '3.8'

services:
  db-mysql:
    image: mysql
    container_name: container-db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festa-mysql-spring-angular
    restart: always
    networks:
      - workspace
    expose:
      - 3306
    
  spring-docker:
    build: 
      dockerfile: Dockerfile
    container_name: container-api-spring-docker
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - workspace
    depends_on:
      - db-mysql

networks:
  workspace:
    driver: bridge